blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/reliable-agents-ai/triads/blob/main/README.md
    about: Check the documentation and guides
  - name: Discussions
    url: https://github.com/reliable-agents-ai/triads/discussions
    about: Ask questions and discuss ideas with the community
  - name: Claude Code Documentation
    url: https://docs.claude.com/en/docs/claude-code
    about: Official Claude Code documentation
